### ISSUE TITLE
Following README results in errors

### ISSUE THREAD

**Issue by pietercolpaert** [TREEcg/Basic-LDES-Server#12]
```
pieter@pieter-Latitude-7400:~/Projects$ git clone git@github.com:TREEcg/Basic-LDES-Server.git bls
Cloning into 'bls'...
remote: Enumerating objects: 578, done.
remote: Counting objects: 100% (578/578), done.
remote: Compressing objects: 100% (293/293), done.
remote: Total 578 (delta 328), reused 483 (delta 247), pack-reused 0
Receiving objects: 100% (578/578), 78.61 KiB | 856.00 KiB/s, done.
Resolving deltas: 100% (328/328), done.
pieter@pieter-Latitude-7400:~/Projects$ cd bls
pieter@pieter-Latitude-7400:~/Projects/bls$ yarn install
yarn install v1.17.3
info No lockfile found.
[1/4] Resolving packages...
warning @dexagod/rdf-retrieval > rdf-ext > @rdfjs/data-model > @types/rdf-js@4.0.2: This is a stub types definition. rdf-js provides its own type definitions, so you do not need this installed.
warning sqlite3 > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
warning sqlite3 > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning sqlite3 > node-gyp > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning sqlite3 > node-gyp > tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
warning sqlite3 > node-gyp > request > har-validator@5.1.5: this library is no longer supported
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@dexagod/rdf-retrieval > rdf-dereference > @comunica/actor-http-proxy@1.22.1" has unmet peer dependency "@comunica/context-entries@^1.0.0".
warning "@dexagod/rdf-retrieval > rdf-serialize > @comunica/actor-rdf-serialize-jsonld@1.22.0" has unmet peer dependency "@comunica/actor-abstract-mediatyped@^1.0.0".
[4/4] Building fresh packages...
success Saved lockfile.
Done in 25.47s.
pieter@pieter-Latitude-7400:~/Projects/bls$ yarn run dev
yarn run v1.17.3
$ nodemon --config nodemon.json --exec yarn start
[nodemon] 2.0.12
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): **/*
[nodemon] watching extensions: js,json,ts
[nodemon] starting `yarn start`
$ yarn run build && node ./bin/server.js
$ yarn run clean && tsc
$ rm -rf dist
Boilerplate/sources/boilerplateSource.ts:1:30 - error TS2307: Cannot find module '@treecg/basic-ldes-server' or its corresponding type declarations.

1 import { Source, Page } from '@treecg/basic-ldes-server';
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Examples/sources/mySource-import.ts:1:28 - error TS2307: Cannot find module '@treecg/basic-ldes-server' or its corresponding type declarations.

1 import {Source, Page} from '@treecg/basic-ldes-server';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Examples/sources/mySource.ts:1:28 - error TS2307: Cannot find module '@treecg/basic-ldes-server' or its corresponding type declarations.

1 import {Source, Page} from '@treecg/basic-ldes-server';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Examples/sources/telraamSource.ts:1:28 - error TS2307: Cannot find module '@treecg/basic-ldes-server' or its corresponding type declarations.

1 import {Source, Page} from '@treecg/basic-ldes-server';
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 4 errors.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[nodemon] process failed, unhandled exit code (2)
[nodemon] 
[nodemon] Either the command has a syntax error,
[nodemon] or it is exiting with reserved code 2.
[nodemon] 
[nodemon] To keep nodemon running even after a code 2,
[nodemon] add this to the end of your command: || exit 1
[nodemon] 
[nodemon] Read more here: https://git.io/fNOAG
[nodemon] 
[nodemon] nodemon will stop now so that you can fix the command.
[nodemon] 
[nodemon] Error
    at Bus.<anonymous> (/home/pieter/Projects/bls/node_modules/nodemon/lib/nodemon.js:158:25)
    at Bus.emit (node:events:406:35)
    at ChildProcess.<anonymous> (/home/pieter/Projects/bls/node_modules/nodemon/lib/monitor/run.js:206:11)
    at ChildProcess.emit (node:events:394:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
Done in 3.77s.
pieter@pieter-Latitude-7400:~/Projects/bls$
```

Any idea what might be happening? Could it be that package.json is not correctly configured?

Can the README.md be updated also with publishing it to NPM instructions?

**Comment by KasperZutterman** [comment]
This commit https://github.com/TREEcg/Basic-LDES-Server/commit/fd7f3784f2321a55784a32a9b582e2bff9af14a7 should fix this issue, the problem was that `/Boilerplate` & `/Examples` are separate NodeJs projects with their own package.json using the root project as a dependency (their dependencies didn't get installed). The root project does not need these for the compilation so the folders are now excluded.
